apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: kubelet-extra-args
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.128.0.0/12
  topology:
    class: kubelet-extra-args
    controlPlane:
      metadata: {}
      replicas: 3
    version: v1.27.0
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: 3
